In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [3]:
pd.options.display.max_columns = 999
pd.options.display.max_rows = 999

# 데이터 불러오기 data

In [4]:
data = pd.read_csv('mid2_2.csv',encoding='euc-kr')

# 질병 별 환자수 데이터 프레임 df1 생성

In [5]:
#질병 별 환자수
#데이터 프레임 컬럼이름만 설정해서 생성
df1 = pd.DataFrame(columns=["name","healthy_count","sick_count",
                            "healthy_rate","sick_rate"] )
#데이터 프레임에 행추가 방식으로 값을 넣어준다.
for i, col in enumerate(data.filter(regex = '^D.{2}_pr').columns):
    df1.loc[i] = [data[col].name] +\
                data[col].value_counts().tolist()+\
                data[col].value_counts(True).tolist()

In [7]:
#데이터 프레임에 병 이름을 나타내는 컬럼 추가
tmp = ["고혈압 현재 유병여부","이상지질혈증현재 유병여부",
                  "뇌졸증","심근경색증","협심증","골관절염","류머티스",
                  "폐결핵","천식","당뇨","갑상선","위암","간암",
                  "대장암","유방암","자궁경부암","폐암","갑상선암",
                  "우울증","아토피피부염","알레르기","신부전",
                  "B형간염","C형간염","간경변증"]

df1["name2"] = tmp

In [8]:
df1

      name healthy_count sick_count  healthy_rate  sick_rate          name2
0   DI1_pr         13294       3836      0.776065   0.223935    고혈압 현재 유병여부
1   DI2_pr         15042       2088      0.878109   0.121891  이상지질혈증현재 유병여부
2   DI3_pr         16827        303      0.982312   0.017688            뇌졸증
3   DI5_pr         16974        156      0.990893   0.009107          심근경색증
4   DI6_pr         16854        276      0.983888   0.016112            협심증
5   DM2_pr         15327       1803      0.894746   0.105254           골관절염
6   DM3_pr         16865        265      0.984530   0.015470           류머티스
7   DJ2_pr         17116         14      0.999183   0.000817            폐결핵
8   DJ4_pr         16826        304      0.982253   0.017747             천식
9   DE1_pr         15630       1500      0.912434   0.087566             당뇨
10  DE2_pr         16767        363      0.978809   0.021191            갑상선
11  DC1_pr         17070         60      0.996497   0.003503             위암
12  DC2_pr         17109         21      0.998774   0.001226             간암
13  DC3_pr         17101         29      0.998307   0.001693            대장암
14  DC4_pr         17082         48      0.997198   0.002802            유방암
15  DC5_pr         17120         10      0.999416   0.000584          자궁경부암
16  DC6_pr         17115         15      0.999124   0.000876             폐암
17  DC7_pr         17033         97      0.994337   0.005663           갑상선암
18  DF2_pr         16639        491      0.971337   0.028663            우울증
19  DL1_pr         16850        280      0.983654   0.016346         아토피피부염
20  DJ8_pr         15299       1831      0.893112   0.106888           알레르기
21  DN1_pr         17077         53      0.996906   0.003094            신부전
22  DK8_pr         17038         92      0.994629   0.005371           B형간염
23  DK9_pr         17116         14      0.999183   0.000817           C형간염
24  DK4_pr         17093         37      0.997840   0.002160           간경변증

In [79]:
df1.sort_values('sick_count',ascending=False)

      name healthy_count sick_count  healthy_rate  sick_rate          name2
0   DI1_pr         13294       3836      0.776065   0.223935    고혈압 현재 유병여부
1   DI2_pr         15042       2088      0.878109   0.121891  이상지질혈증현재 유병여부
20  DJ8_pr         15299       1831      0.893112   0.106888           알레르기
5   DM2_pr         15327       1803      0.894746   0.105254           골관절염
9   DE1_pr         15630       1500      0.912434   0.087566             당뇨
18  DF2_pr         16639        491      0.971337   0.028663            우울증
10  DE2_pr         16767        363      0.978809   0.021191            갑상선
8   DJ4_pr         16826        304      0.982253   0.017747             천식
2   DI3_pr         16827        303      0.982312   0.017688            뇌졸증
19  DL1_pr         16850        280      0.983654   0.016346         아토피피부염
4   DI6_pr         16854        276      0.983888   0.016112            협심증
6   DM3_pr         16865        265      0.984530   0.015470           류머티스
3   DI5_pr         16974        156      0.990893   0.009107          심근경색증
17  DC7_pr         17033         97      0.994337   0.005663           갑상선암
22  DK8_pr         17038         92      0.994629   0.005371           B형간염
11  DC1_pr         17070         60      0.996497   0.003503             위암
21  DN1_pr         17077         53      0.996906   0.003094            신부전
14  DC4_pr         17082         48      0.997198   0.002802            유방암
24  DK4_pr         17093         37      0.997840   0.002160           간경변증
13  DC3_pr         17101         29      0.998307   0.001693            대장암
12  DC2_pr         17109         21      0.998774   0.001226             간암
16  DC6_pr         17115         15      0.999124   0.000876             폐암
7   DJ2_pr         17116         14      0.999183   0.000817            폐결핵
23  DK9_pr         17116         14      0.999183   0.000817           C형간염
15  DC5_pr         17120         10      0.999416   0.000584          자궁경부암

In [9]:
#환자가 100명 이하인 병들
df1.loc[df1.sick_count <= 100]

      name healthy_count sick_count  healthy_rate  sick_rate  name2
7   DJ2_pr         17116         14      0.999183   0.000817    폐결핵
11  DC1_pr         17070         60      0.996497   0.003503     위암
12  DC2_pr         17109         21      0.998774   0.001226     간암
13  DC3_pr         17101         29      0.998307   0.001693    대장암
14  DC4_pr         17082         48      0.997198   0.002802    유방암
15  DC5_pr         17120         10      0.999416   0.000584  자궁경부암
16  DC6_pr         17115         15      0.999124   0.000876     폐암
17  DC7_pr         17033         97      0.994337   0.005663   갑상선암
21  DN1_pr         17077         53      0.996906   0.003094    신부전
22  DK8_pr         17038         92      0.994629   0.005371   B형간염
23  DK9_pr         17116         14      0.999183   0.000817   C형간염
24  DK4_pr         17093         37      0.997840   0.002160   간경변증

# 복합 질병 여부와 비율 데이터프레임 각각

In [22]:
# 함수 : 질병에 따라 복합질병 환자 여부
# 데이터프레임으로 반환

def double1(data=data,df1=df1, x="DE1_pr", q = "q1"):
    #컬럼 이름 생성 (df1 필요)
    tmp = []
    for i in df1.name:
        tmp.append(i + q)
    
    #임시 데이터프레임 생성 
    df3 = pd.DataFrame(columns = tmp)
    
    #요소별 곱을 통해 다른 질병과 같이 걸린 여부 생성
    #(data, df1 필요)
    for i in range(len(df1)):
        tmp2 = data[x] * data[df1.name[i]]
        df3.iloc[:,i] = tmp2
    
    #복합적으로 걸린 사람 비율
    #임시 데이터프레임 생성
    df4 = pd.DataFrame(columns=["name","name2","sum","rate"])
    for i in range(len(df1)):
        df4.loc[i] = [df1.name[i]]+\
                     [df1.name2[i]]+\
                     [df3.sum()[i]]+\
                     [round(df3.sum()[i]/df1.sick_count[i], 3)]
                            
    return df3, df4

In [23]:
df3, df4 = double1(data=data,df1=df1, x="DE1_pr", q="q1")

In [24]:
df3

,DI1_prq1,DI2_prq1,DI3_prq1,DI5_prq1,DI6_prq1,DM2_prq1,DM3_prq1,DJ2_prq1,DJ4_prq1,DE1_prq1,DE2_prq1,DC1_prq1,DC2_prq1,DC3_prq1,DC4_prq1,DC5_prq1,DC6_prq1,DC7_prq1,DF2_prq1,DL1_prq1,DJ8_prq1,DN1_prq1,DK8_prq1,DK9_prq1,DK4_prq1
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17125,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17126,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17127,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17128,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17129,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
df4

      name          name2     sum   rate
0   DI1_pr    고혈압 현재 유병여부   927.0  0.242
1   DI2_pr  이상지질혈증현재 유병여부   567.0  0.272
2   DI3_pr            뇌졸증    98.0  0.323
3   DI5_pr          심근경색증    60.0  0.385
4   DI6_pr            협심증    69.0  0.250
5   DM2_pr           골관절염   315.0  0.175
6   DM3_pr           류머티스    44.0  0.166
7   DJ2_pr            폐결핵     5.0  0.357
8   DJ4_pr             천식    50.0  0.164
9   DE1_pr             당뇨  1500.0  1.000
10  DE2_pr            갑상선    45.0  0.124
11  DC1_pr             위암    10.0  0.167
12  DC2_pr             간암     6.0  0.286
13  DC3_pr            대장암     7.0  0.241
14  DC4_pr            유방암     7.0  0.146
15  DC5_pr          자궁경부암     0.0  0.000
16  DC6_pr             폐암     4.0  0.267
17  DC7_pr           갑상선암     9.0  0.093
18  DF2_pr            우울증    68.0  0.138
19  DL1_pr         아토피피부염    21.0  0.075
20  DJ8_pr           알레르기    90.0  0.049
21  DN1_pr            신부전    22.0  0.415
22  DK8_pr           B형간염    15.0  0.163
23  DK9_pr           C형간염     4.0  0.286
24  DK4_pr           간경변증    11.0  0.297

# 복합 질병 환자수, 비율 탐색

In [35]:
df3 , df4 = double1(data=data,df1=df1, x="DE1_pr", q="q1")

In [36]:
df4.sort_values('rate',ascending=False).head(6)

      name  name2     sum   rate
9   DE1_pr     당뇨  1500.0  1.000
21  DN1_pr    신부전    22.0  0.415
3   DI5_pr  심근경색증    60.0  0.385
7   DJ2_pr    폐결핵     5.0  0.357
2   DI3_pr    뇌졸증    98.0  0.323
24  DK4_pr   간경변증    11.0  0.297

In [51]:
#상위 6개씩 확인
for i in range(len(df1)):
    df3 , df4 = double1(data=data,df1=df1,
                        x=df1.name[i], q="q1")
    print(df1.name2[i])
    print(df4.sort_values('rate',ascending=False).head(6))
    print()
    print()

고혈압 현재 유병여부
      name        name2     sum   rate
0   DI1_pr  고혈압 현재 유병여부  3836.0  1.000
2   DI3_pr          뇌졸증   209.0  0.690
21  DN1_pr          신부전    36.0  0.679
4   DI6_pr          협심증   172.0  0.623
9   DE1_pr           당뇨   927.0  0.618
3   DI5_pr        심근경색증    96.0  0.615


이상지질혈증현재 유병여부
      name          name2     sum   rate
1   DI2_pr  이상지질혈증현재 유병여부  2088.0  1.000
4   DI6_pr            협심증   119.0  0.431
3   DI5_pr          심근경색증    62.0  0.397
9   DE1_pr             당뇨   567.0  0.378
2   DI3_pr            뇌졸증   107.0  0.353
21  DN1_pr            신부전    17.0  0.321


뇌졸증
      name  name2    sum   rate
2   DI3_pr    뇌졸증  303.0  1.000
3   DI5_pr  심근경색증   12.0  0.077
4   DI6_pr    협심증   21.0  0.076
23  DK9_pr   C형간염    1.0  0.071
16  DC6_pr     폐암    1.0  0.067
9   DE1_pr     당뇨   98.0  0.065


심근경색증
      name  name2    sum   rate
3   DI5_pr  심근경색증  156.0  1.000
16  DC6_pr     폐암    2.0  0.133
4   DI6_pr    협심증   33.0  0.120
21  DN1_pr    신부전    5.0  0.094
9   DE1_pr     당뇨   60.0  0.040
2   DI3_pr    뇌졸증   12.0  0.040


협심증
      name  name2    sum   rate
4   DI6_pr    협심증  276.0  1.000
3   DI5_pr  심근경색증   33.0  0.212
21  DN1_pr    신부전   10.0  0.189
2   DI3_pr    뇌졸증   21.0  0.069
11  DC1_pr     위암    4.0  0.067
8   DJ4_pr     천식   18.0  0.059


골관절염
      name name2     sum   rate
5   DM2_pr  골관절염  1803.0  1.000
4   DI6_pr   협심증    93.0  0.337
6   DM3_pr  류머티스    87.0  0.328
24  DK4_pr  간경변증    11.0  0.297
18  DF2_pr   우울증   145.0  0.295
23  DK9_pr  C형간염     4.0  0.286


류머티스
      name name2    sum   rate
6   DM3_pr  류머티스  265.0  1.000
18  DF2_pr   우울증   32.0  0.065
8   DJ4_pr    천식   18.0  0.059
5   DM2_pr  골관절염   87.0  0.048
22  DK8_pr  B형간염    4.0  0.043
14  DC4_pr   유방암    2.0  0.042


폐결핵
     name          name2   sum   rate
7  DJ2_pr            폐결핵  14.0  1.000
8  DJ4_pr             천식   1.0  0.003
9  DE1_pr             당뇨   5.0  0.003
0  DI1_pr    고혈압 현재 유병여부   6.0  0.002
1  DI2_pr  이상지질혈증현재 유병여부   4.0  0.002
5  DM2_pr           골관절염   2.0  0.001


천식
      name   name2    sum   rate
8   DJ4_pr      천식  304.0  1.000
19  DL1_pr  아토피피부염   21.0  0.075
23  DK9_pr    C형간염    1.0  0.071
7   DJ2_pr     폐결핵    1.0  0.071
6   DM3_pr    류머티스   18.0  0.068
4   DI6_pr     협심증   18.0  0.065


당뇨
      name  name2     sum   rate
9   DE1_pr     당뇨  1500.0  1.000
21  DN1_pr    신부전    22.0  0.415
3   DI5_pr  심근경색증    60.0  0.385
7   DJ2_pr    폐결핵     5.0  0.357
2   DI3_pr    뇌졸증    98.0  0.323
24  DK4_pr   간경변증    11.0  0.297


갑상선
      name name2    sum   rate
10  DE2_pr   갑상선  363.0  1.000
17  DC7_pr  갑상선암   12.0  0.124
14  DC4_pr   유방암    3.0  0.062
21  DN1_pr   신부전    3.0  0.057
5   DM2_pr  골관절염   93.0  0.052
18  DF2_pr   우울증   25.0  0.051


위암
      name name2   sum   rate
11  DC1_pr    위암  60.0  1.000
13  DC3_pr   대장암   2.0  0.069
16  DC6_pr    폐암   1.0  0.067
12  DC2_pr    간암   1.0  0.048
4   DI6_pr   협심증   4.0  0.014
22  DK8_pr  B형간염   1.0  0.011


간암
      name name2   sum   rate
12  DC2_pr    간암  21.0  1.000
24  DK4_pr  간경변증   4.0  0.108
23  DK9_pr  C형간염   1.0  0.071
22  DK8_pr  B형간염   4.0  0.043
13  DC3_pr   대장암   1.0  0.034
11  DC1_pr    위암   1.0  0.017


대장암
      name name2   sum   rate
13  DC3_pr   대장암  29.0  1.000
12  DC2_pr    간암   1.0  0.048
11  DC1_pr    위암   2.0  0.033
24  DK4_pr  간경변증   1.0  0.027
22  DK8_pr  B형간염   2.0  0.022
9   DE1_pr    당뇨   7.0  0.005


유방암
      name   name2   sum   rate
14  DC4_pr     유방암  48.0  1.000
6   DM3_pr    류머티스   2.0  0.008
10  DE2_pr     갑상선   3.0  0.008
20  DJ8_pr    알레르기  13.0  0.007
19  DL1_pr  아토피피부염   2.0  0.007
9   DE1_pr      당뇨   7.0  0.005


자궁경부암
      name          name2   sum   rate
15  DC5_pr          자궁경부암  10.0  1.000
17  DC7_pr           갑상선암   2.0  0.021
18  DF2_pr            우울증   1.0  0.002
0   DI1_pr    고혈압 현재 유병여부   3.0  0.001
1   DI2_pr  이상지질혈증현재 유병여부   2.0  0.001
13  DC3_pr            대장암   0.0  0.000


폐암
      name  name2   sum   rate
16  DC6_pr     폐암  15.0  1.000
11  DC1_pr     위암   1.0  0.017
3   DI5_pr  심근경색증   2.0  0.013
22  DK8_pr   B형간염   1.0  0.011
17  DC7_pr   갑상선암   1.0  0.010
2   DI3_pr    뇌졸증   1.0  0.003


갑상선암
      name  name2   sum   rate
17  DC7_pr   갑상선암  97.0  1.000
15  DC5_pr  자궁경부암   2.0  0.200
23  DK9_pr   C형간염   1.0  0.071
16  DC6_pr     폐암   1.0  0.067
10  DE2_pr    갑상선  12.0  0.033
8   DJ4_pr     천식   6.0  0.020


우울증
      name  name2    sum   rate
18  DF2_pr    우울증  491.0  1.000
21  DN1_pr    신부전    8.0  0.151
6   DM3_pr   류머티스   32.0  0.121
15  DC5_pr  자궁경부암    1.0  0.100
4   DI6_pr    협심증   26.0  0.094
8   DJ4_pr     천식   26.0  0.086


아토피피부염
      name   name2    sum   rate
19  DL1_pr  아토피피부염  280.0  1.000
8   DJ4_pr      천식   21.0  0.069
24  DK4_pr    간경변증    2.0  0.054
20  DJ8_pr    알레르기   91.0  0.050
14  DC4_pr     유방암    2.0  0.042
21  DN1_pr     신부전    2.0  0.038


알레르기
      name   name2     sum   rate
20  DJ8_pr    알레르기  1831.0  1.000
19  DL1_pr  아토피피부염    91.0  0.325
8   DJ4_pr      천식    92.0  0.303
14  DC4_pr     유방암    13.0  0.271
22  DK8_pr    B형간염    15.0  0.163
23  DK9_pr    C형간염     2.0  0.143


신부전
      name  name2   sum   rate
21  DN1_pr    신부전  53.0  1.000
23  DK9_pr   C형간염   1.0  0.071
4   DI6_pr    협심증  10.0  0.036
3   DI5_pr  심근경색증   5.0  0.032
18  DF2_pr    우울증   8.0  0.016
9   DE1_pr     당뇨  22.0  0.015


B형간염
      name name2   sum   rate
22  DK8_pr  B형간염  92.0  1.000
24  DK4_pr  간경변증  10.0  0.270
23  DK9_pr  C형간염   3.0  0.214
12  DC2_pr    간암   4.0  0.190
13  DC3_pr   대장암   2.0  0.069
16  DC6_pr    폐암   1.0  0.067


C형간염
      name name2   sum   rate
23  DK9_pr  C형간염  14.0  1.000
24  DK4_pr  간경변증   2.0  0.054
12  DC2_pr    간암   1.0  0.048
22  DK8_pr  B형간염   3.0  0.033
21  DN1_pr   신부전   1.0  0.019
17  DC7_pr  갑상선암   1.0  0.010


간경변증
      name   name2   sum   rate
24  DK4_pr    간경변증  37.0  1.000
12  DC2_pr      간암   4.0  0.190
23  DK9_pr    C형간염   2.0  0.143
22  DK8_pr    B형간염  10.0  0.109
13  DC3_pr     대장암   1.0  0.034
19  DL1_pr  아토피피부염   2.0  0.007

# 발병여부 비율 조사
---
### 해당병의 발병여부가 다른 병의 발병여부에 관계가 매우 높은 것들(기준 0.1 이상)
- 고혈압 : 뇌졸증, 신부전, 협심증, 당뇨, 심근경색증
- 이상지질혈증 : 협심증, 심근경색증, 당뇨, 뇌졸중, 신부전
- 심근경색증 : 폐암, 협심증
- 협심증 : 심근경색증, 신부전
- 골관절염 : 협심증, 류머티스, 간경변증, 우울증, C형간염
- 당뇨 : 신부전, 심근경색증, 폐결핵, 뇌졸증, 간경변증
- 갑상선 : 갑상선암
- 간암 : 간경변증
- 갑상선암 : 자궁경부암
- 우울증 : 신부전, 류머티스, 자궁경부암
- 알레르기 : 아토피피부염, 천식, 유방암, B형간염, C형간염
- B형간염 : 간경변증, C형간염, 간암 
- 간경변증 : 간암, C형간염, B형간염
---
### 해당병의 발병여부가 다른 병의 발병여부에 관계가 매우 낮은 것들 (기준 0.1 이하)
- 뇌졸증,류머티스, 폐결핵, 천식, 위암, 대장암, 유방암, 자궁경부암
- 폐암, 아토피피부염, 신부전, C형간염

In [44]:
#고혈압이 다른 병과 연관이 많이 됨을 볼 수 있다.
df3 , df4 = double1(data=data,df1=df1,
                        x=str(df1.name[0]), q="q1")
print(df1.name2[0])
df4.sort_values('rate',ascending=False)

고혈압 현재 유병여부

      name          name2     sum   rate
0   DI1_pr    고혈압 현재 유병여부  3836.0  1.000
2   DI3_pr            뇌졸증   209.0  0.690
21  DN1_pr            신부전    36.0  0.679
4   DI6_pr            협심증   172.0  0.623
9   DE1_pr             당뇨   927.0  0.618
3   DI5_pr          심근경색증    96.0  0.615
1   DI2_pr  이상지질혈증현재 유병여부  1220.0  0.584
5   DM2_pr           골관절염   855.0  0.474
16  DC6_pr             폐암     7.0  0.467
24  DK4_pr           간경변증    17.0  0.459
7   DJ2_pr            폐결핵     6.0  0.429
8   DJ4_pr             천식   123.0  0.405
12  DC2_pr             간암     8.0  0.381
6   DM3_pr           류머티스    95.0  0.358
23  DK9_pr           C형간염     5.0  0.357
13  DC3_pr            대장암    10.0  0.345
18  DF2_pr            우울증   165.0  0.336
10  DE2_pr            갑상선   111.0  0.306
11  DC1_pr             위암    18.0  0.300
15  DC5_pr          자궁경부암     3.0  0.300
17  DC7_pr           갑상선암    29.0  0.299
22  DK8_pr           B형간염    22.0  0.239
14  DC4_pr            유방암    10.0  0.208
20  DJ8_pr           알레르기   251.0  0.137
19  DL1_pr         아토피피부염    35.0  0.125

# 여러개의 질병인 가진사람들의 수

In [57]:
df5 = data[df1.name].copy()

In [58]:
df5.head()

,DI1_pr,DI2_pr,DI3_pr,DI5_pr,DI6_pr,DM2_pr,DM3_pr,DJ2_pr,DJ4_pr,DE1_pr,DE2_pr,DC1_pr,DC2_pr,DC3_pr,DC4_pr,DC5_pr,DC6_pr,DC7_pr,DF2_pr,DL1_pr,DJ8_pr,DN1_pr,DK8_pr,DK9_pr,DK4_pr
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [61]:
df5['sum'] = df5.sum(axis=1)

In [63]:
df5.head()

,DI1_pr,DI2_pr,DI3_pr,DI5_pr,DI6_pr,DM2_pr,DM3_pr,DJ2_pr,DJ4_pr,DE1_pr,DE2_pr,DC1_pr,DC2_pr,DC3_pr,DC4_pr,DC5_pr,DC6_pr,DC7_pr,DF2_pr,DL1_pr,DJ8_pr,DN1_pr,DK8_pr,DK9_pr,DK4_pr,sum
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [65]:
#질병 수에 따른 개수
df5['sum'].value_counts()

0.0     9073
1.0     4404
2.0     2143
3.0      994
4.0      342
5.0      117
6.0       44
7.0       10
8.0        2
11.0       1
Name: sum, dtype: int64

In [75]:
#병이 유무 (병없다 False, 병 있다 True)
df5['any_sick_tf'] = (df5['sum'] != 0)

df5['any_sick'].value_counts()

False    9073
True     8057
Name: any_sick, dtype: int64